Fix icons on hourly view
hacf-fr/lovelace-meteofrance-weather-card pull request #103
Opened 2023-04-29 13:33 UTC by vingerha

Shows night-time icons correctly, which is only visible in hourly view

2023-04-29 15:12 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
Pourquoi avoir répété les valeurs de weatherIconsDay dans weatherIconesNight ?
...weatherIconesDay permet justement de les reprendre et les valeurs remplacées par les nouvelles définies !

2023-04-29 15:17 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
J'avais des soucis avec les icones et je n'ais pas trouvé une solution qui marche sans les copier 100%

2023-04-29 15:18 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
Je pense pareque p.e. clear: est dans les deux groupes...mais pas sûre

2023-04-29 15:21 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
Si t'as des idées a analyser/tester...je le fait

2023-04-29 15:23 UTC, dx44 requested changes

2023-04-29 15:23 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
Cette méthode est déjà utilisée dans une autre partie du code avec (condition,sun) ligne 256 ! Sa signature ne doit pas changer.
L'utilisation de this.hass.states["sun.sun"] n'est pas suffisant pour le choix des icônes ?

2023-04-29 15:26 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
sans datetime, il prend que la situation de 'maintenant'...les icones sont bon pour la nuit que quand c'est la nuit 'maintenant'
Datetime permet de utiliser les heures des forecast, pas 'maintenant'
Pour les prév. des jours ça ne change rien.

2023-04-29 15:28 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
Comme tu peux voir dans l'autre PR
sans mes corrections...il montre la soleille au lieu de la lune

2023-04-29 15:56 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
OK je vois pour l'affichage daily. Par contre coté dev il ne faut pas hésiter à segmenter le code et créer une méthode getSunState(datetime) {}. Cette méthode peut retourner ce que sun.state doit retourner mais avec l'état pondéré par le datetime.
Cela permet d'aérer et de mieux comprendre le code.
Désolé d'être pointilleux, surtout si tu n'es pas développeur cela peut sembler superflu ce qui n'est pas le cas !

2023-04-29 15:58 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
je suis surtout PAS développeur :) 
Hacker/Architecte/Testeur/ChefProjets/etc...pas dev
je vais voir demain ou...plus tard.
merci!

2023-04-29 16:01 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
La concaténation de dictionnaire fonctionne correctement donc le soucis doit être ailleurs.
Pour exemple j'ai reproduit les 2 listes 👍🏻 
![image](https://user-images.githubusercontent.com/13116057/235312025-f488f9bb-fe60-4fa6-b687-5f57a3d09f8f.png)

2023-04-29 16:03 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
OK..je vais REvoir aussi... chez moi j'avais que des mauvaise icones

2023-04-30 03:54 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +const weatherIconsNight = {
J'ai trouvé le soucis mais je ne peux pas l'expliquer.
Quand j'enlève 'windy-variant', ça marche aussi pour partlycloudy
Donc, cet setup marche:
```
const weatherIconsNight = {
  ...weatherIconsDay,	
  clear: "night",
  sunny: "night",
  partlycloudy: "cloudy-night-3",
};
```
et ça non
```
const weatherIconsNight = {
  ...weatherIconsDay,	
  clear: "night",
  sunny: "night",
  partlycloudy: "cloudy-night-3",
  "windy-variant": "cloudy-night-3",
};
```

2023-04-30 06:46 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
Donc, après heures ....
J'ai essaié de refaire le code mais ça ne marche pas et je suis perdu, stp un peu d'aide
Ça marche:
```
  getWeatherIcon(condition, datetimehourly) {
	var nextsetting = this.hass.states["sun.sun"].attributes.next_setting
	var nextrising = this.hass.states["sun.sun"].attributes.next_rising  
    return `${this._config.icons
      ? this._config.icons
      : "/local/community/lovelace-meteofrance-weather-card/icons/"
      }${datetimehourly && ((datetimehourly > nextsetting && datetimehourly < nextrising) || (datetimehourly < nextsetting && datetimehourly < nextrising && nextrising < nextsetting))
        ? weatherIconsNight[condition]
        : weatherIconsDay[condition]
      }.svg`;
  }
```
et ça ne marche pas
```
  getWeatherIcon(condition, datetimehourly) {
	var nextsetting = this.hass.states["sun.sun"].attributes.next_setting
	var nextrising = this.hass.states["sun.sun"].attributes.next_rising  
    return `${this._config.icons
      ? this._config.icons
      : "/local/community/lovelace-meteofrance-weather-card/icons/"
      }${isNightTime(datetimehourly)
        ? weatherIconsNight[condition]
        : weatherIconsDay[condition]
      }.svg`;
  }

  isNightTime(datetimehourly) {
	var nextsetting = this.hass.states["sun.sun"].attributes.next_setting
	var nextrising = this.hass.states["sun.sun"].attributes.next_rising 
	  return `${datetimehourly && ((datetimehourly > nextsetting && datetimehourly < nextrising) || (datetimehourly < nextsetting && datetimehourly < nextrising && nextrising < nextsetting))
	  }`;
  }
```

2023-04-30 09:38 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
never mind...missed the adding "this."

2023-04-30 10:33 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
@dx44 Je suis prêt avec les changements, as-tu encore des commentaires ?
Sinon, je propose de le laisser comme ça pendant quelques jours puisque je revois les résultats

2023-05-01 11:11 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
Malheureusement je ne peux pas faire de modif sur ce fichier de cette PR car il est dans sur ton dépôt (d'où le fait de faire des PRs depuis un clône et non un fork).
Donc je te propose les modifications suivantes :
- extraction de la méthode isNightTime() pour qu'elle n'appartienne pas à getWeatherIcon() mais en soit utilisée en paramètre
- adaptation de la méthode getPhenomenaText() pour utiliser isNightTime() également
- le calcul de l'état de nuit dans la méthode isNightTime() peut être plus robuste, par exemple avec cette implémentation :
```javascript
  isNightTime(datetimehourly) {
    const sun = this.hass.states["sun.sun"];
    if (!sun) { return false}

    let next_rising = new Date(sun.attributes.next_rising);
    let next_setting = new Date(sun.attributes.next_setting);

    const thistime = datetimehourly ? new Date(datetimehourly) : new Date()

    return (thistime > next_setting && thistime < next_rising)
  }
```

2023-05-01 11:25 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
OK, je vais easyer de suivre tes idées. 
1. extraction: dans ce cas là je vais appeler isNighttime de "renderDailyForecast", non?
ensuite getWeatherIcon(condition, datetimehourly, isDaily) > getWeatherIcon(condition, isDaily)
2. phehomena: OK
3. de ton exemple, j'espère que t'as compris que  (thistime > next_setting && thistime < next_rising) ne suffit pas si t'as vu mon code...

Et mecri pour l 'avis clone vs. fork... une prochaine fois.

2023-05-01 11:32 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
En gros, nommer 'renderDailyForecast' était trops limité avec 'daily' comme données
Mieux de l'avoir nommé renderForecastDetail (ou sorte) et paramétriser p.e. 'fc_time' au lieu de daily.... je le refait ou pas?

2023-05-01 11:53 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
Refait... j'espère que c'est mieux.... je ne suis pas trops heureux de t'embêter avec mes non-dev trucs..mais j'apprends

2023-05-01 13:52 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
non..pas bon, oublié phenomena... je le fait maintenant

2023-05-01 15:00 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, datetimehourly) {
Donc, c'est fait, j'ai revu quelques petites choses et ne pas (!) touch;e phenomena
Ce derniér est pour la texte dans la carte qui montré 'maintenant' et ne touche pas forecast donc l'implementation reste correcte

2023-05-01 17:33 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
Le isDaily est inutile comme info 😉 , juste isNight suffit.

2023-05-01 17:34 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +          daily.condition.toLowerCase(), isDaily, this.isNightTime(daily.datetime)
Supprimer isDaily

2023-05-01 17:35 UTC, dx44 commented on dist/meteofrance-weather-card.js
>    getPhenomenaText(phenomena, sun) {
Remplacer sun par isNight

2023-05-01 17:35 UTC, dx44 commented on dist/meteofrance-weather-card.js
>      return `${sun && sun.state == "below_horizon"
Faire juste le test ${isNight

2023-05-01 17:40 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +      }${!isDaily && isNight
Juste le test isNight

2023-05-02 04:28 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
Non, parceque isDaily determine si MeteoFrance est sur Daily ou Hourly et ça change le contient de la carte. Daily horaires sont dans la nuit toujours et isNight + isDaily est nécessaire

2023-05-02 04:29 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +          daily.condition.toLowerCase(), isDaily, this.isNightTime(daily.datetime)
voir ci-dessus

2023-05-02 04:29 UTC, vingerha commented on dist/meteofrance-weather-card.js
>    getPhenomenaText(phenomena, sun) {
voir ci-dessus

2023-05-02 04:31 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +      }${!isDaily && isNight
voir ci-dessus

2023-05-02 04:36 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +      }${!isDaily && isNight
Car le comportement et données entre daily/hourly est différent je préfère normalement d'avoir rederDaily et redeerHourly ou (!) renderNight vs renderDay au lieu de cramer le tout dans une procedure qui devient un peu confusant....renderDaily fait daily/hourly et jour/nuit

2023-05-02 04:36 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +      }${!isDaily && isNight
Mais bon...

2023-05-03 10:55 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
Le isDaily n'est pas à être gérer dans le getWeatherIcon ! Il faut bien séparer la logique.

2023-05-03 11:01 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
Avant de faire plus (c'est pas trops efficace ces aller/retrour)
Si j'ajoute ce logique 'isDaily dan isNightTime, et j'utilise que isNight dans getWeatherIcon, t'es d'accord?

2023-05-03 11:03 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
Je doute de plus en plus si le tout vaut la peine, il y a tant des cartes qui gêrent bien les icones...c'est que poour avoir un truc 'français''... a la base cette carte mérite une maj plus importante
Donc, c'est la dernière action que je fais...sinon tant-pis.

2023-05-03 16:06 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
> Avant de faire plus (c'est pas trops efficace ces aller/retrour) Si j'ajoute ce logique 'isDaily dan isNightTime, et j'utilise que isNight dans getWeatherIcon, t'es d'accord?

C'est ce que je pensais également comme logique 👍🏻 
Après ça je merge et je release une bétâ.

2023-05-03 16:08 UTC, dx44 commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
> Je doute de plus en plus si le tout vaut la peine, il y a tant des cartes qui gêrent bien les icones...c'est que poour avoir un truc 'français''... a la base cette carte mérite une maj plus importante Donc, c'est la dernière action que je fais...sinon tant-pis.

Humm je suis preneur d'exemple 👍🏻

2023-05-04 04:59 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
Merci... rien contre toi/tes remarques... il faut avoir un gardien contre n'importe-quoi .... je vais voir demain ou w/e

2023-05-05 04:15 UTC, vingerha commented on dist/meteofrance-weather-card.js
> +  getWeatherIcon(condition, isDaily, isNight) {
C'est fait, merci

2023-05-05 11:56 UTC, dx44 approved these changes
LGTM

2023-05-05 11:56 UTC, merged