Modification des mn pour oneHourLabel
hacf-fr/lovelace-meteofrance-weather-card pull request #26
Opened 2020-10-25 11:25 UTC by Axellum

Le titre de la prévision n'est pas en accord avec les minutes #19. Remis en accord avec l'api.

2020-10-25 12:54 UTC, dx44 commented
Alors la modification a été apporté par @ioull pour refléter ce que propose le site météo france où c'est toutes les 5 min. puis à partir des 20 min. c'est toutes les 10 min.

![image](https://user-images.githubusercontent.com/13116057/97107783-9d67df80-16c9-11eb-9923-e5dde70f58d8.png)

La question ici est de savoir si l'intégration météo france est à modifier. Je vais poser la question.

2020-10-25 21:11 UTC, dx44 requested changes
Je suis d'accord avec cette correction mais le positionnement du temps n'est plus correcte sous la barre de prévision.

2020-10-25 22:11 UTC, ioull commented
Je ne suis pas d'accord avec cette modification :-)

2020-10-26 00:08 UTC, oncleben31 commented
C'est comme vous voulez ca reste une estimation: 30 min ou 35 minutes c'est pareil pour moi.
L'API renvoie une date absolue qui permet de construire les  intervals du sensor. Donc soit nous préférons une cohérence avec l'API soir nous préférons une cohérence avec l'affichage du site web. 

J'aurai tendance à préférer légèrement a deuxième pour éviter d'avoir régulièrement une question de pourquoi l'intégration et le site web ont des affichages différents ?

2020-10-26 09:24 UTC, ioull commented
C'est également mon avis, il y a du être ce entre l'API et ce qui est présenté ... Par contre ce qui est visible doit être cohérent sinon on va passer son temps a expliquer ;-) 
Et en plus ça semble plus cohérent l'affichage que des dates en 35,45,55 et un dernier carré de  5 au lieu des 10 ...

2020-10-26 09:29 UTC, Axellum commented
En fais pour moi cela m est égale, même si idéalement il aurait fallu changer l infos du survole des 3 dernières cases. Mais vus que cela n est pas à ma porter...

2020-10-26 12:20 UTC, Axellum commented
Peut être comme ça, avec une petite condition supplémentaire?

2020-10-28 21:26 UTC, dx44 commented
Je reviens sur ce PR car je ne pense que ce soit à la carte de s'adapter à l'API suivant les infos présentés par le site. Nous devons prendre ce que l'entité nous donne et non pas commencé à mettre des petits sparadraps.
@oncleben31 l'entité xx_next_rain retourne telles quelles les données de l'API ? d'après la capture d'écran du site, il semble qu'il y est une projection de toutes les 5 min. pendant 1 heure, ensuite c'est uniquement les indicateurs de temps en dessous qui sont à 5 puis 10 min. d'interval.

2020-10-30 09:49 UTC, oncleben31 commented
@dx44 J'i pas compris la question peux tu reformuler ?

2020-11-04 16:32 UTC, oncleben31 commented
C'est pas moi qui choisi les intervalles. C'est bien l'API qui les donnes avec des timestamp.
Je trouve que la proposition de @ioull de supprimer la notion de temps dans le tooltip et de ne garder que le type de pluie.

2020-11-20 18:43 UTC, dx44 commented
Solution apportée dans un PR récent.

2020-11-20 18:43 UTC, closed without merging