Update README.md
hacf-fr/lovelace-meteofrance-weather-card pull request #29
Opened 2020-10-25 17:08 UTC by Axellum

idem info.md

2020-10-25 21:09 UTC, dx44 requested changes
Pour ma part je n'ai pas le .js à définir manuellement en ressource, ni à saisir manuellement le nom de l'entité à la sélection de la carte, elle directement disponible dans la liste des cartes personnalisées.
as-tu dû vraiment faire manuellement ou c'est par habitude ? Désolé de demander ça mais j'ai fais la manip plusieurs fois (avec suppression de la carte, du dépôt) et c'est automatique chez moi. Peut-être pour ma version HA 0.118.dev.

2020-10-26 09:53 UTC, Axellum commented
En fais j ai u le problème sur une des premières versions, et chercher un peu pourquoi cela ne marchai pas, du coup j'y suis aller par habitude ^^. Je regarde sur je peut tester.

2020-10-26 10:30 UTC, Axellum commented
Ok, à priori pas besoin effectivement, je fais le changement :).

2020-10-26 10:34 UTC, Axellum commented
Par contre ce serais bien de stocker les images ici, si tu peu les mettre je ferais la maj des adresses (et peut être les refaire avec la dernière version, ou je les refais et te les passe, comme tu veut).

2020-10-26 12:42 UTC, dx44 approved these changes
Je l'approuve en 1er jet.
En configuration le point 2/ et 3/ ne sont à faire il me semble, à la sélection de la carte c'est l'éditeur visuel qui s'affiche, il prend la 1ère entity weather si elle existe.

2020-10-26 12:42 UTC, merged