Modification de certains icônes pour une meilleur différenciation.
hacf-fr/lovelace-meteofrance-weather-card pull request #33
Opened 2020-10-27 18:46 UTC by Axellum

Modification de certains icônes pour une meilleur différenciation, avec les icônes d'origine.
Permet aussi à d'autres jeux d’icônes d'améliorer la visibilités des différents statuts.
A tester voir les changements vous conviennent (j'ai essayé de faire aux mieux avec les icônes présent) -Surtout snowy-4 a la place de rainy-7-. 
A voir si je différencie aussi l'orage, en ajoutant ou doublant un icônes d'origine existant.

2020-10-28 17:09 UTC, Axellum commented
Si vous souhaitez ajouter les 3 nouveaux icônes, ne pas faire cette MAJ. J'ai aussi proposer ces icônes sur une issus du fork bramkragten.

2020-11-06 17:46 UTC, dx44 requested changes
Je ne peux pas accépter ce PR sans les icônes manquant.
Il faut ajouter les nouveaux.

2020-11-06 18:16 UTC, Axellum commented
Je ne peut pas les up, faut que je te les envois (je n'est pas les droit pour up).

2020-11-08 12:38 UTC, dx44 commented
Cette PR est supplantée par la #50

2020-11-08 12:38 UTC, closed without merging